### ISSUE TITLE
Delete this repo?

### ISSUE THREAD

**Issue by phkrief** [eclipse-opensmartclide/smartclide-Backend-REST-Client#1]
Dear @schlotze, @deanone ,

Should we delete this repo?
It is empty

**Comment by deanone** [comment]
@phkrief I believe we can and we should (in order to start reducing the number of repos).

**Comment by goncalorolo** [comment]
It was us (UNP) who asked for the creation of this repository but it ended up being unnecessary. It can therefore be deleted.
